Allanx2000
tahnik/devRantron pull request #1
Opened 2017-02-23 13:26 UTC by allanx2000

Start prototyping the post control and needed assets

2017-02-24 14:56 UTC, tahnik requested changes

2017-02-24 14:56 UTC, tahnik commented on src/main/java/Main.java
> +        api.getRants(Sort.ALGO, 10, 0).thenAcceptAsync(results -> {
This is not the place to get the rants. In a controller maybe? Also, you should use thenAccept()

2017-02-24 14:56 UTC, tahnik commented on src/main/java/controllers/PostControl.java
> +public class PostControl extends BorderPane{
This class looks like a model, not a controller. Also, why is extending borderpane? You should use an FXML instead and modify that via controllers.

2017-02-24 14:59 UTC, allanx2000 commented on src/main/java/controllers/PostControl.java
> +public class PostControl extends BorderPane{
https://docs.oracle.com/javase/8/javafx/fxml-tutorial/custom_control.htm

I followed this to make it a reuseable control

2017-02-24 15:17 UTC, allanx2000 commented on src/main/java/Main.java
> +        api.getRants(Sort.ALGO, 10, 0).thenAcceptAsync(results -> {
Ah OK for supply and then accept confused, thought then accept her to be async as well.

This was just for testing the PostControl and highlight the issue I'm having with the image

2017-02-28 23:41 UTC, tahnik approved these changes

2017-02-28 23:41 UTC, merged